apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: eb4o3niel-nodejs 
  janus-idp.io/tekton: eb4o3niel-nodejs
  backstage.io/kubernetes-id: eb4o3niel-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eb4o3niel-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml