apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eb4o3niel-nodejs
  janus-idp.io/tekton: eb4o3niel-nodejs
  backstage.io/kubernetes-id: eb4o3niel-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eb4o3niel-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
