apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eb4o3niel-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eb4o3niel-nodejs 
  name: eb4o3niel-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: eb4o3niel-nodejs 
